// flow-typed signature: 7d022986f0fc5d9c1e0342faaac0c2a4
// flow-typed version: <<STUB>>/react-scripts_v1.0.17/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-scripts' {
  declare module.exports: any;
}
